### ISSUE TITLE
Optional parameter [kmsauth token] cannot be passed in

### ISSUE THREAD

**Issue by jaymed** [Netflix/bless#65]
If passing in a 10th parameter [kmsauth token], there is ValueError displayed.

```
Traceback (most recent call last):
  File "./bless_client/bless_client.py", line 98, in <module>
    main(sys.argv[1:])
  File "./bless_client/bless_client.py", line 51, in main
    bastion_command, public_key_filename, certificate_filename = argv
ValueError: too many values to unpack
```

**Comment by avoidik** [comment]
https://github.com/Netflix/bless/pull/63

**Comment by marranz** [comment]
I added it to the like 51 and works.

```
    region, lambda_function_name, bastion_user, bastion_user_ip, remote_usernames, bastion_ips, \
        bastion_command, public_key_filename, certificate_filename, kmsauth_token = argv
```

**Comment by russell-lewis** [comment]
This is working for me now.  Let me know if you still have issues.
